catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project k_kem_enc
set_top k_kem_enc
# v++ -g, -D, -I, --advanced.prop kernel.k_kem_enc.kernel_flags
add_files "/home/xcarril/dilithium-update/ML-KEM/encapsulation/xsrc/k_kem_enc.cpp" -cflags " -D KYBER_K=2 -I /home/xcarril/dilithium-update/ML-KEM/encapsulation/xinclude "
add_files "/home/xcarril/dilithium-update/ML-KEM/encapsulation/xinclude/kernel.hpp" -cflags " -D KYBER_K=2 -I /home/xcarril/dilithium-update/ML-KEM/encapsulation/xinclude "
open_solution -flow_target vitis solution
set_part xcu280-fsvh2892-2L-e
create_clock -period 300.000000MHz -name default
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
config_dataflow -fifo_depth 100
# v++ --advanced.param compiler.deadlockDetection
config_export -deadlock_detection none
config_export -version 0.0.1
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format xo -ipname k_kem_enc
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
